# DarkEggKit develop
platform :ios, '13.0'
use_frameworks!

target 'DarkEggKit_Example' do
  pod 'DarkEggKit', :path => '../'
  pod 'DarkEggKit/PaddingLabel', :path => '../'
  pod 'DarkEggKit/PopupMessage', :path => '../'
  pod 'DarkEggKit/SideMenu', :path => '../'
  pod 'DarkEggKit/AnimatedImageView', :path => '../'
  # pod 'DarkEggKit/ButtonMenu', :path => '../'
  pod 'DarkEggKit/DoughnutChart', :path => '../'
  pod 'DarkEggKit/BarChart', :path => '../'

  target 'DarkEggKit_Tests' do
    inherit! :search_paths
  end
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
    # Check out: https://github.com/flutter/flutter/issues/123852
    # Workaround for Xcode 14.3:
    # system('sed -i \'\' \'44s/readlink/readlink -f/\' \'Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh\'')
end
