# 
platform :ios, '12.0'
use_frameworks!

target 'DarkEggKit_Example' do
  pod 'DarkEggKit', :path => '../'
  pod 'DarkEggKit/PaddingLabel', :path => '../'
  pod 'DarkEggKit/PopupMessage', :path => '../'
  pod 'DarkEggKit/SideMenu', :path => '../'
  pod 'DarkEggKit/AnimatedImageView', :path => '../'
  # pod 'DarkEggKit/ButtonMenu', :path => '../'
  pod 'DarkEggKit/DoughnutChart', :path => '../'
  pod 'DarkEggKit/BarChart', :path => '../'

  target 'DarkEggKit_Tests' do
    inherit! :search_paths
  end
end
