# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os:
  - osx
language: swift
osx_image: xcode11
branches:
  only:
    - develop
script:
  - swift build
  - swift test

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

# script:
# - set -o pipefail && xcodebuild -workspace Example/DarkEggKit.xcworkspace -scheme DarkEggKit-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' ONLY_ACTIVE_ARCH=NO | xcprettyTIVE_ARCH=NO | xcpretty
# - set -o pipefail && xcodebuild test -workspace Example/DZPopupMessageView.xcworkspace -scheme DZPopupMessageSample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.1' ONLY_ACTIVE_ARCH=NO | xcprettyTIVE_ARCH=NO | xcpretty
# - pod lib lint
# - pod lib lint
