name: Check Build
#
on: 
  push:
    branches:
      - fix/xcode11
    tag:
      - 0.3.1

jobs:
  build:
    name: Build and Test(TODO)
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone X']

    steps:
      # Checkout
      - name: Checkout source code
        uses: actions/checkout@master
      # Pod install
      - name: Run pod install
        run: |
          cd Example
          pod install
      # Build
      - name: Build
        run: |
          xcodebuild -workspace Example/DarkEggKit.xcworkspace -scheme DarkEggKit-Example -sdk iphonesimulator -destination '${destination}' ONLY_ACTIVE_ARCH=NO
      env:
        CI: true
